packaging_format = 2

id = "actual"
name = "Actual"
description.en = "Local-first personal finance tool"
description.fr = "Premier outil de finances personnelles local"

version = "23.8.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
admindoc = "https://actualbudget.github.io/docs/"
code = "https://github.com/actualbudget/actual-server"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "850M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/actualbudget/actual-server/archive/refs/tags/v23.8.1.tar.gz"
        sha256 = "841fd4c8e1d79e8e61b7f633ee63e768da866af3f614017e07b90e5f1e82b828"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data/user-files", "data/server-files"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5006

    [resources.apt]
    packages = "sqlite3"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
