packaging_format = 2

id = "actual"
name = "Actual"
description.en = "Local-first personal finance tool"
description.fr = "Premier outil de finances personnelles local"

version = "23.7.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
admindoc = "https://actualbudget.github.io/docs/"
code = "https://github.com/actualbudget/actual-server"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/actualbudget/actual-server/archive/refs/tags/v23.7.1.tar.gz"
        sha256 = "4f4587191d266e2e1f9d95b9d7d4dd0ded053697d7f4c7e1177b4053d9065914"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["user-files", "server-files"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5006

    [resources.apt]
    packages = "sqlite3"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
