packaging_format = 2

id = "actual"
name = "Actual"
description.en = "Local-first personal finance tool"
description.fr = "Premier outil de finances personnelles local"

version = "24.6.0~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
admindoc = "https://actualbudget.github.io/docs/"
code = "https://github.com/actualbudget/actual-server"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "850M"
ram.runtime = "50M"



[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.release_cycle]
    ask.en = "Upgrade cycle"
    ask.fr = "Cycle de mises à jours"
    help.en = "Stable is updated every Release, Edge is updated every Commit."
    help.fr = "Stable est mis à jour à chaque version, Edge est mis à jour chaque engagement."
    type = "select"
    choices.stable = "Install Stable Version (recommended)"
    choices.edge = "Install Edge Version"
    default = "stable"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/actualbudget/actual-server/archive/refs/tags/v24.6.0.tar.gz"
        sha256 = "2348b5748edbf6a2f83a1e899f21fc9f03737cfa79529da0bb57081fa490e2bd"
        autoupdate.strategy = "latest_github_tag"
        [resources.sources.edge]
        url = "https://github.com/actualbudget/actual-server/archive/1af5ab09e92954235cc3efff74c274c10fb4a2e9.tar.gz"
        sha256 = "c62cb71234198311acb2143bb32904ceac45f3c406ae2ff1e111406c9eded9d9"
        autoupdate.upstream = "https://github.com/actualbudget/actual"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data/user-files", "data/server-files"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5006

    [resources.apt]
    packages = "sqlite3"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
